"!/usr/bin/vim

set background=dark
colors zenburn "Load the color scheme
set nocompatible

set guifont=Monospace\ 12
set colorcolumn=80 "Draw line at 80 columns

let maplocalleader=","

execute pathogen"infect()
filetype indent plugin on
syntax on "Syntax highlighting

"Make latex fast again
au FileType tex setlocal nocursorline

set number "Show line numbers
set wildmenu "Complete Vim commands
set cursorline "Highlight the cursor line

set lazyredraw
set tabstop=4 shiftwidth=4 expandtab "Tabs -> 4 spaces

"Search tweaks
set incsearch "Search before pressing enter, incremental search
set ignorecase smartcase "Ignore case when searching, unless capital letters are used

set linebreak "Only break at words

"Open file explorer
nmap - :Explore<Enter>

"Tab keymaps
nmap tt :tabnew<Enter>
nmap t<Left> :tabprevious<Enter>
nmap t<Right> :tabnext<Enter>
nmap tq :tabclose<Enter>

"Move in wrapped lines
nmap <Up> gk
nmap <Down> gj
imap <Up> <C-o>gk
imap <Down> <C-o>gj

"Place regular tab
imap <S-Tab> <C-V><Tab>

"set listchars=eol:¶,tab:>-,trail:·,extends:>,precedes:<,space:·
"set list

"hi GroupA cterm=LightGray ctermbg=LightGray ctermfg=LightGray guibg=LightGray
"hi GroupB cterm=LightGray ctermbg=LightGray ctermfg=LightGray guibg=LightGray
"match GroupA / \+$/
"match GroupB /\t/
"hi Specialkey ctermfg=LightGray
"match Specialkey /\s\+$/



" " General
" set number                     " Show line numbers
" set linebreak                  " Break lines at word (requires Wrap lines)
" set showbreak=+++              " Wrap-broken line prefix
" set textwidth=100              " Line wrap (number of cols)
" set showmatch                  " Highlight matching brace
" set spell                      " Enable spell-checking
" set visualbell                 " Use visual bell (no beeping)

" set hlsearch                   " Highlight all search results
" set smartcase                  " Enable smart-case search
" set gdefault                   " Always substitute all matches in a line
" set ignorecase                 " Always case-insensitive
" set incsearch                  " Searches for strings incrementally

" set autoindent                 " Auto-indent new lines
" set cindent                    " Use 'C' style program indenting
" set expandtab                  " Use spaces instead of tabs
" set shiftwidth=4               " Number of auto-indent spaces
" set smartindent                " Enable smart-indent
" set smarttab                   " Enable smart-tabs
" set softtabstop=4              " Number of spaces per Tab

" " Advanced
" set confirm                    " Prompt confirmation dialogs
" set ruler                      " Show row and column ruler information

" set autochdir                  " Change working directory to open buffer
" set autowriteall               " Auto-write all file changes

" set undolevels=1000            " Number of undo levels
" set backspace=indent,eol,start " Backspace behaviour


" " Generated by VimConfig.com
